config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  get 'wedding' => 'home#wedding'
  get 'weekend' => 'home#weekend'
  get 'transport' => 'home#transport'
  get 'accommodation' => 'home#accommodation'
  get 'more' => 'home#more'

  resources :rsvps do
    # get 'add_guest', on: :member
    resources :guests
  end

  resources :contributions
  resources :photos

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :guest
end

app/models/dietary_requirement.rb
class DietaryRequirement < ActiveRecord::Base
  belongs_to :guest
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :rsvp
  has_many :dietary_reqirements
  has_many :contributions
  has_one :transport
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  has_many :guests
  accepts_nested_attributes_for :guests
end

app/models/transport.rb
class Transport < ActiveRecord::Base
  belongs_to :guest
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :find_guest, only: [:update, :destroy]
  before_action :find_rsvp, only: [:new, :create]


  def new
    @guest = @rsvp.guests.build
    # @guest.save
    respond_to do |format|
      format.html { render :new, layout: false }
    end
  end


  # def create
  #   @guest = Guest.create(guest_params)
  #   @rsvp << @guest
  #   if @guest.persisted?
  #     respond_to do |format|
  #       format.html { render :show, layout: false }
  #     end
  #   else
  #     render text: @guest.errors.full_messages.join(", "), status: 500
  #   end
  # end
  # #
  # #
  # # def update
  # #   @guest.update_attributes(guest_params)
  # # end
  #
  #
  # def destroy
  #   @guest.destroy
  #   # render nothing: true
  #   respond_to.js { render nothing: true }
  #   # end
  # end


  private
    def guest_params
      params.require(:guest).permit(:name, :email, :rsvp_id)
    end

    def find_guest
      @guest = Guest.find(params[:id])
    end

    def find_rsvp
      @rsvp = Rsvp.find(params[:rsvp_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :find_rsvp, only: [:update]


  def new
    @rsvp = Rsvp.new
    # @rsvp = Rsvp.create
    @guest = @rsvp.guests.build
    # @guest.save
  end


  def create
    @rsvp = Rsvp.create(rsvp_params)
    if @rsvp.persisted?
      respond_to do |format|
        format.html   { render 'guests/show', layout: false, locals: {rsvp: @rsvp, guest: @rsvp.guests[0]} }
        format.js     { @rsvp.id }
      end
    else
      render :new
    end
  end


  # def update
  #   @guest.update_attributes(rsvp_params[:guests_attributes]["0"])
  #   # @rsvp = Rsvp.create
  #   # @guest = Guest.create(rsvp_params[:guests_attributes]["0"])
  #   # @rsvp.guests << @guest
  #
  #   if @guest.persisted?
  #     respond_to do |format|
  #       format.html { render @guest, layout: false }
  #     end
  #   else
  #     render text: @guest.errors.full_messages.join(", "), status: 500
  #   end
  # end


  private
    # def find_guest
    #   @guest = Guest.find(params[:guest_id])
    # end

    def find_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    def rsvp_params
      params.require(:rsvp).permit(:guest_ids, guests_attributes: [:id, :name, :email])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/guests/new.haml
%fieldset
  = simple_form_for [@rsvp, @guest] do |g|
    = g.input :name, wrapper_html: {class: "col-xs-5"}
    = g.input :email, wrapper_html: {class: "col-xs-7"}

app/views/guests/show.haml
.row
  %fieldset(class="#{rsvp.id}")
    .col-xs-4
      = guest.name
    .col-xs-5
      = guest.email
    .col-xs-2
      %a.btn.pull-left#guest-delete(href="#{rsvp_guest_path(rsvp, guest)}" method="delete")
        %i.glyphicon.glyphicon-remove

app/views/home/_menu.haml
%nav(class="navbar #{'navbar-fixed-top' unless current_page?('/')}" )
  .container-fluid

    .navbar-header.text-center
      %button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#navbar")
        %i.fa.fa-bars.fa-3x

    .collapse.navbar-collapse#navbar
      %ul.nav.nav-justified
        - unless current_page?('/')
          %li= link_to "Home", '/'
        %li= link_to "Wedding", wedding_path
        %li= link_to "Weekend", weekend_path
        %li= link_to "Transport", transport_path
        %li= link_to "Accommodation", accommodation_path
        %li= link_to "RSVP", new_rsvp_path
        %li= link_to "More", more_path

app/views/home/accommodation.haml
Accommodation

Camping
Royal National Park, LOT 1 Lady Wakehurst Dr, Lilyvale NSW 2508, Australia
There is plenty of room to camp! We suggest you bring a tent, sleeping bag, pillow and torch. The property has toilets, showers and running water. Plus a river for a quick dip.

Glamping

Wow bell tents pop-up hotel (if they fucking reply ever!)


Other
The property is located about 7 minutes drive from Otford. We suggest you jump onto airbnb.

app/views/home/more.haml
.intro Well since you're still here, here are some puns!

.outro Please email your suggestions here: xxxx

app/views/home/show.haml
#home-container

  .image-container

    =image_tag("bottom-right.png", id: "image-b-r")
    =image_tag("bottom-left.png", id: "image-b-l")
    =image_tag("top-right.png", id: "image-t-r")

  .container-fluid
    .row#fixed-border
      .col-lg-8.col-lg-offset-2
        .row
          .text-center#text-container
            #header-container
              .h3#names
                Brooke and Kath's
              .h3#wedding
                WEDDING
            #info-container
              .h4#date
                26th November 2016
              .h4#venue
                Lilyvale in the Royal National Park

        .row
          .col-lg-12
            =render "menu"

app/views/home/transport.haml
Transport

app/views/home/wedding.haml
.row
  .col-lg-8.col-lg-offset-2
    .panel.panel-success
      .panel-body
        %div Welcome! We're getting married.
        %br
        %div It's a camping wedding on a beautiful property in the Royal National Park called Lilyvale. The ceremony is on Saturday 26 November but we are hoping you can also join us the evening prior (Friday 25 November) for camping, delicious woodfired pizza and good times. It would be great if you stayed with us on Saturday night after the ceremony too. Think about the huge breakfast cooking extravaganza you will miss out on if you don't stay.
        %br
        %div There's plenty of room for tents, caravans, swags and even an option to glamp. Running water and toilets are available with all options. If camping is not for you there are a places close by that you can rest your weary heads.
        %br
        %div Scroll through the pages to find more information about accommodation, transport, activities and things to bring.
        %br
        %div Be warned there will be plenty of food, drinks and dancing.
        %br
        %div Looking forward to celebrating with you!
    .well.well-lg
      .panel
        %strong
          4
          %sup 00
        Arriving and mingling

      .panel
        %strong
          4
          %sup 30
        Vowing

      .panel
        %strong
          5
          %sup 00
        Grazing

      .panel
        %strong
          5
          %sup 30
        Hora-ing (dancing)

      .panel
        %strong
          6
          %sup 00
        Dining & Speeching

      .panel
        %strong
          8
          %sup 30
        Dancing & Desserting

      .panel
        %strong
          10
          %sup 00
        Deserting (for those going on the bus)

      .panel
        %strong
          10
          %sup 00
        Perhaps some late-night bonfiring and other shenanaging

app/views/home/weekend.haml
%fieldset(style="border: 1px black solid")
  %span(style="margin-left: 0.4em; padding: 0.2em 0.4em; display: inline-block; border: none")
    Text within the box

%p We'd love you to join us for our Wedding ceremony and party on Saturday 26th November.
%p But we'd love it even more if you'd join us for the whole weekend!

app/views/layouts/_flash_messages.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>


<!-- might need these for devise:
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <title><%= content_for?(:title) ? yield(:title) : "Page Title" %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
<%= render 'layouts/flash_messages' %>
<%= render 'home/menu' unless current_page?('/') %>
<%= yield %>
</body>
</html>

app/views/rsvps/_rsvp.haml
.row
  .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2.col-xs-10.col-xs-offset-1
    = simple_form_for @rsvp do |r|
      = r.input :friday_dinner
      = r.input :saturday_breakfast
      = r.input :wedding
      = r.input :sunday_breakfast

      = r.input :friday_camping
      = r.input :saturday_camping

app/views/rsvps/new.haml
.modal.fade.show#rsvpModal
  .modal-dialog
    .modal-content

      .modal-body.clearfix

        %button.close(type="button" data-dismiss="modal")
          %span(aria-hidden="true") &times;

        .row
          %h3.text-center RSVP
          %h5.text-center Please respond by 1 August 2016


        %fieldset#guests-heading
          %form-group.col-xs-5
            %label.control-label(for="rsvp_guests_attributes_0_name")
              Guest name
          %form-group.col-xs-7
            %label.control-label(for="rsvp_guests_attributes_0_email")
              Email

        #guests-container
        #guests-form
          %fieldset
            = simple_form_for @rsvp do |r|
              = r.simple_fields_for :guests do |g|
                = g.input :name, label: false, wrapper_html: {class: "col-xs-5"}
                = g.input :email, label: false, wrapper_html: {class: "col-xs-7"}

        %fieldset#add-guest-container
          .col-xs-1
            %a.btn.pull-left#add_guest(href="#" data-remote="true")
              %i.glyphicon.glyphicon-plus
          .col-xs-5
            %p#add-btn Add another guest

      .modal-footer#response
        %form
          .row
            .col-xs-6#rsvp-yes
              %button.btn.btn-default.btn-lg.btn-block(href="#" type="submit" form="edit_guest_#{@guest.id}" )
                Count me in!
            .col-xs-6#rsvp-no
              %button.btn.btn-default.btn-lg.btn-block
                Nah, got better things to do

      .modal-footer.hide#details
        = render 'rsvp'